### ISSUE TITLE
Launched game can't go ingame

### ISSUE THREAD

**Issue by tokenspins** [Ciensprog/Aerial-Launcher#1]
Currently when I enter the game in any game mode the game kicks me out with the message:

> You were removed from the match due to internet lag, your IP address or computer, VPN usage, or cheating

As far as I understand, the launcher currently generates an exchange code to launch the game with the IOS or Android client.
But to start the game it has to be generated with launcherAppClient2, otherwise the game will kick you out as described above. I would create a pull request but I can't code. I only know how certain things work.

PS: Thank you for creating an alternative launcher for the discontinued Potato Launcher. The laucher was my daily companion and I loved the many functions it had. And this project looks very promising so far.

**Comment by Ciensprog** [comment]
Thank you very much for creating the first issue 🙌 this means much for me even if a Pull Request is not created.

The game launch button does exactly what you describes: generate an exchange code using the launcherAppClient2 client, this is used to run Fortnite with the selected account.

I'll check what could happen and try to fix it in an update as soon as possible.

It's a pleasure for me to know that you are interested in the project 🙌 gradually more features will be added that I hope will be useful to the community 💪
