### ISSUE TITLE
Launching gives an error and doesn't start the game.

### ISSUE THREAD

**Issue by coolboy2002** [Ciensprog/Aerial-Launcher#8]
Launching the game doesn't work. It will say: An update is required to continue. Please restart Fortnite to download the latest patch. I checked my Epic Games Launcher and the game is up to date. 

![afbeelding](https://github.com/Ciensprog/Aerial-Launcher/assets/72800303/4fbd4cc7-da21-4c61-800a-d59324df3935)

**Comment by Ciensprog** [comment]
Hi @coolboy2002!

I've been doing some testing for this feature but I can't reproduce this issue :c

Could you check if you are using the correct installation folder? On the gear icon (top, next to the launch game button). I don't know if you are using multiple installations or something else 😅

![image](https://github.com/Ciensprog/Aerial-Launcher/assets/26677431/9c67ea70-8c73-49e5-a923-2f1426a6db71)

By default is using `C:\Program Files\Epic Games\Fortnite\FortniteGame\Binaries\Win64` folder.

**Comment by coolboy2002** [comment]
Thank you for your response!

I use a different installation folder and have changed it according to the right folder. This is the game starting up giving an error. The thing is that if I start it from the Epic Games Launcher or Potato it works perfectly fine.

**Comment by Ciensprog** [comment]
Could you share a screenshot of the error you get?

It's curious because some friends can run perfectly fine without some kind of error 🤔
